---
- name: This playbook is used to install apache package
  hosts: all
  become: yes
  tasks:
    - name: installing the apache package
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present
    - name: this is used to copy /sourcecode to /var/www/html
      copy:
        src: /sourcecode/
        dest: /var/www/html/
    - name: start apache2 service
      service:
        name: apache2
        state: started
        enabled: yes
    - name: enable port 8080
      lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen'
        insertafter: '^#Listen'
        line: Listen 8080