---
- name: "This is the Multiline format playbook"
  hosts: all
  become: yes
  tasks:
    - copy: src=/etc/group
            dest=/tmp
            owner=ranga
            group=ranga
            mode=0664
    - file: path:/tmp/gcp
            state:directory
    - apt:  name:apache2
            state:present 