---
- name: This playbook file demonstrate Hash loops
  hosts: all
  become: yes
  tasks:
    - name: this task used to copy particular file into particular directory
      copy:
        src: "{{ item.a }}"
        dest: "{{ item.b }}"
      with_items:
        - { a: '/etc/passwd', b: '/tmp' }
        - { a: '/etc/group', b: '/mnt' }
        - { a: '/etc/fstab', b: 'opt' }


        