---
- name: This playbook demonstrate loops
  hosts: all
  become: yes
  tasks:
    - name: this task is used to copy file
      copy:
        src: "{{ item }}"
        dest: /tmp
      with_items:
        - /etc/passwd
        - /etc/fstab
        - /etc/shadow
        - /etc/group
    - name: this task is used to create directories
      file:
        path: " {{ item }}"
        state: directory
      with_item:
        - /tmp/mycloud1
        - /tmp/mycloud2
    - name: this task used to copy the file into directories
      copy:
        src: /etc/passwd
        dest: "{{ item }}"
      with_item:
        - /tmp/mycloud1
        - /tmp/mycloud2