---
- name: This playbook is used to Provisioning EC2 instance
  hosts: localhost/all
  become: yes
  tasks:
    - ec2:
        aws_access_key: 
        aws_secret_key:
        Key_name: ansible-key
        group:  Ansible-SG
        instance_type:  t2.micro
        image:  ami-
        wait: yes
        wait_timeout: 500
        count: 1
        instance_tags:
          Name: Prod-team
        monitoring: yes
        region: us-west-2
        assign_public_ip: yes
        vpc_subnet_id:
