---
- name: This playbook is used to stop multiple EC2 instances
  hosts: localhost/all
  become: yes
  tasks:
    - local_action:
        aws_access_key: 
        aws_secret_key:
        module: ec2
        instance_tags:
          Name: 
            - Prod-team
            - Admin-team
        state: stopped
        region: us-west-2
