---
- name: This playbook is used to create VPC subnets
  hosts: all
  become: yes
  tasks:
    - ec2_vpc_subnet:
        aws_access_key:
        aws_secret_key:
        az: us-west-2a
        cidr: 172.22.1.0/24
        region: us-west-2
        state: present
        vpc_id: vpc id here
        resource_tags:
          Name: App-subnet       