---
- name: this playbook is used to detach elastic block storage(ebs) volume to an instance
  hosts: localhost
  become: yes
  tasks:
    - ec2_vol:
        aws_access_key:
        aws_secret_key:
        id: volume id here  
        instance: None
        zone: us-west-2b
        region: us-west-2
        
       


