---
- name: This playbook involves var_files where variables mentioned in another yaml file 
  hosts: all
  become: yes
  vars_file:
    - /myvariables/vars.yaml
  tasks:
    - name: "This task is used to create directory {{ mydir }}"
      file:
        path: "{{ mydir }}"
        state: directory
    - name: "This task is used to copy from {{ myfile }} to {{ mydir }}"
      copy:
        src: "{{ myfile }}"
        dest: "{{ mydir }}"
        mode: 0666
    - name: "This task is used to installing {{ mypkg }} packages"
      apt:
        name: "{{ mypkg }}"
        update_cache: yes
        state: present
